#!/bin/bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source_code_directory="$current_directory"/code
build_directory="$current_directory"/../build
install_directory="$current_directory"/../install

export PATH=$PATH:"$source_code_directory"/external/bass/libraries/64bit
rm -r "$install_directory"
mkdir "$install_directory"
rm -r "$build_directory"
mkdir "$build_directory"
cd "$build_directory"
ccmake "$source_code_directory" -DCMAKE_INSTALL_PREFIX="$install_directory" -DCMAKE_BUILD_TYPE=Debug -DARCHITECTURE=64bit
make
make install
