SET(NAME "Visore")
SET(PACKAGE "visore")
SET(VERSION_MAJOR "0")
SET(VERSION_MINOR "0")
SET(VERSION_PATCH "1")
SET(SHORT_DESCRIPTION "Vinyl Sound Refurbisher")
SET(LONG_DESCRIPTION "Visore is a software project for the sound restoration of vinyl (gramophone) records. Visore filters the noise caused by scratches, dust and degradation and amplifies the sound where necessary.")
SET(MAINTAINER "Christoph Stallmann")
SET(EMAIL "info@visore.org")
SET(HOMEPAGE "http://www.visore.org")
SET(INSTALL_LOCATION "/usr/local/visore")
SET(LICENSE "LGPLv2.1")
SET(COPYRIGHT "Copyright (c) 2011-2012 Christoph Stallmann")
